version: 2.1

orbs:
  python: circleci/python@2.0.3
  docker: circleci/docker@2.1.1

jobs:
  build_and_test:
    executor: python/default # use the default executor defined within the orb
    steps:
      - checkout # checkout source code
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
      - run:
          name: Run flake8
          command: flake8
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  check-and-build-only:
      executor: docker/machine
      steps:
        - checkout
        - docker/check
        - docker/build:
            image: $DOCKER_LOGIN/$DOCKER_NAME

workflows:
  build_test:
    jobs:
      - build_and_test
      - check-and-build-only:
          requires:
            - build_and_test
