version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  build_and_test:
    executor: python/default # use the default executor defined within the orb
    steps:
      - checkout # checkout source code
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
      - run:
          name: Run flake8
          command: flake8
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
      - run:
          name: build and push Docker image
          command: |
            docker build -t matthlc92/$IMAGE_NAME:$TAG .

      - run:
          name: build and push Docker image
          command: |
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push matthlc92/$IMAGE_NAME:$TAG



workflows:
  build_test:
    jobs:
      - build_and_test
