version: 2.1

orbs:
  python: circleci/python@2.0.3
  docker: circleci/docker@2.1.1

jobs:
  build_and_test:
    executor: python/default # use the default executor defined within the orb
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
      - run:
          name: Run flake8
          command: flake8
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  docker_build_and_push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: ${DOCKER_LOGIN}/$IMAGE_NAME

workflows:

  build_test:
    jobs:
      - build_and_test
      - docker_build_and_push:
          context: ENV_VAR_LETTING
          requires:
            - build_and_test

